### ISSUE TITLE
Unity WebGL failing in Chrome

### ISSUE THREAD

**Issue by bnjbvr** [mozilla/arewefastyet#119]
```
exception thrown: TypeError:
WEBAudio.audioContext.listener.setVelocity is not a
function,TypeError: WEBAudio.audioContext.listener.setVelocity is not
a function
    at _JS_Sound_SetListenerVelocity
(http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:1:248406)
    at yff (http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:5:337250)
    at Phf (http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:5:376321)
    at B5e (http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:5:43410)
    at t4e (http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:5:15200)
    at Array.u4e
(http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:5:15582)
    at I5e (http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:5:48166)
    at Array.jdf
(http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:5:315399)
    at bdd (http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:33:408529)
    at Array.x8f
(http://localhost:8000/benchmarks/unity-webgl/Data/WebGLBenchmarks.js:45:788145)
```

When I use the Chrome console, WEBAudio.audioContext.listener.set
proposes to auto-complete to setOrientation/setPosition, but not
setVelocity.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/mozilla/arewefastyet/commit/856de7c7be53470b8feb79d59c3f52a8346b8a52

**Comment by fabiensanglard** [comment]
Just happened to me, exact same issue and error message. Using chrome 66.0.3359.139.
