### ISSUE TITLE
windows: many "Connection reset by peer" errors after submitting

### ISSUE THREAD

**Issue by bnjbvr** [mozilla/arewefastyet#122]
When running under Windows, I see many "Connection reset by peer" errors in the logs, after the browser has sent results through the /submit endpoint (this is for a remote benchmark). This error is probably shown by the webserver, which shares stdout with the `execute.py` command. The results are still submitted and displayed on AWFY, but it'd be nice to figure out what's going here and to try to solve/hide the issue.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "server.py", line 30, in handle_one_request
    SimpleHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
```

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
